
server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: springboot-week03


app:
  name: 企业后台管理系统 开发环境
  version: 3.0.8
  description: springboot 3.5.11 实战项目
  envs: ["dev", "test", "prod"]
  author:
    name: cookie
    website: https://github.com/cookie-code
    email: test@qq.com

  tokens: 2000
  enabled: true

sms:
  ytx:
    serverIp: ${CLOOPEN_SERVER_IP}
    serverPort: ${CLOOPEN_SERVER_PORT}
    accountSid: ${CLOOPEN_ACCOUNT_SID}
    accountToken: ${CLOOPEN_ACCOUNT_TOKEN}
    appId: ${CLOOPEN_APP_ID}
    to: "13585456936"
    templateId: "1"

